Update recache script to work with modern distributions (#66)
* Deprecate plain http

* Improve echo

* Add signatures for active maintainers

diff --git a/util/recache b/util/recache
--- a/util/recache
+++ b/util/recache
@@ -17,10 +17,10 @@ function cachefile() {
     local localname=$(echo $1 | tr '/' '-')
     local nv=$2
 
-    if wget -q -O $localname "http://nodejs.org/dist/v$nv/$filename"; then
+    if wget -q -O $localname "https://nodejs.org/dist/v$nv/$filename"; then
         md5sum "$localname" > "$localname.md5"
     else
-        echo "$filename not found at http://nodejs.org/dist/v$nv/$filename" && return 0
+        echo "$filename not found at https://nodejs.org/dist/v$nv/$filename" && return 0
     fi
 
     # RHEL/centos7 does not ship with a parent shasum function.
@@ -69,6 +69,12 @@ if which gpg > /dev/null; then
         4ED778F539E3634C779C87C6D7062848A1AB005C \
         A48C2BEE680E841632CD4E44F07496B3EB3C1762 \
         B9E2F5981AA6E0CD28160D9FF13993A75599653C \
+        141F07595B7B3FFE74309A937405533BE57C7D57 \
+        74F12602B6F1C4E913FAA37AD3A89613643B6201 \
+        61FC681DFB92A079F1685E77973F295594EC4689 \
+        890C08DB8579162FEE0DF9DB8BEAB4DFCF555EF4 \
+        C82FA3AE1CBEDC6BE46B9360C43CEC45C17AB93C \
+        108F52B48DB57BB0CC439B2997B01419BD92F80A \
         ; do
         gpg --batch --keyserver hkps://keyserver.ubuntu.com --recv-keys "$key" ||
             gpg --batch --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys "$key" ||
@@ -98,15 +104,15 @@ for nv in "${versions[@]}"; do
     # Verify signed SHASUMS file to ensure it can be trusted
     # Versions after 4.0.0 use shasum's 256 algorithm, check for both
     SHASUMFILE="SHASUMS.txt.asc"
-    if ! wget -q -O $SHASUMFILE "http://nodejs.org/dist/v$nv/$SHASUMFILE"; then
+    if ! wget -q -O $SHASUMFILE "https://nodejs.org/dist/v$nv/$SHASUMFILE"; then
         echo "$SHASUMFILE not found" && rm $SHASUMFILE
         SHASUMFILE="SHASUMS256.txt.asc"
-        if ! wget -q -O $SHASUMFILE "http://nodejs.org/dist/v$nv/$SHASUMFILE"; then
+        if ! wget -q -O $SHASUMFILE "https://nodejs.org/dist/v$nv/$SHASUMFILE"; then
             echo "$SHASUMFILE not found. No SHASUM file found for v$nv, exiting." && exit 1
         fi
     fi
 
-    echo "Verifying signature of nodejs SHASUMS.txt.asc"
+    echo "Verifying signature of nodejs $SHASUMFILE"
     gpg --verify < $SHASUMFILE
 
     cachefile node-v$nv-linux-x64.tar.gz $nv
